name: Build Image Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "alpine"
      REGISTRY: "docker.io/schmillin"
      REGISTRY_USER: "schmillin"
    stepsi:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: schmillin
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: schmillin/alpine:latest
