name: Build Image
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: alpine
      REGISTRY: docker.io/dylanschmittle
      REGISTRY_USER: dylanschmittle
      REGISTRY_PASSWORD: '${{ secrets.REGISTRY_REDHAT_IO_USER }}'
    steps:
      - uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: actions/checkout@v2
      - uses: redhat-actions/buildah-build@v2
        with:
          image: alpine
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile.alpine
      - uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ secrets.REGISTRY }}
